import Foundation

// Top-level statements are only legal in main.swift, so the runner lives here
// and the suites live next door in NotesManagerTests.swift.

runAllTests()
runGlassTintTests()
runOrderedListTests()
runBulletListTests()
runThemeNoteTests()
runCelebrationTests()
runInteractionTests()
runUILayerTests()
runBackgroundRectTests()
runBackgroundWashDiscriminationTests()
runHighlightTests()
runEmphasisTests()
runEmphasisWiringTests()
runPerNoteFontTests()
runDeleteKeepsCurrentNoteTests()
runCodeBlockTests()
runReminderDirectiveTests()
runReminderNotesManagerTests()
runResizableCardTests()
runUpdateCheckerTests()
runImageMarkdownVisibilityTests()
runImageLineLayoutTests()
runImageAtomicReferenceTests()
runImageCaretTests()
runImageGlyphWidthTests()
runImageGlyphClickTests()
runCoverageGapTests()
runFoldedMarkerLayoutTests()
runFormattingShortcutTests()
runLinkClickTests()
runBoldWeightTests()
runSelectionResidueTests()
runHeadingBoldTests()
runAppearanceContrastTests()
runMotionTests()
runEdgeRevealTests()
runVoiceOverTests()

print("\n\(checks - failures)/\(checks) checks passed")
if failures > 0 {
    print("\(failures) FAILED")
    exit(1)
}
print("all green")
